// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example // import "github.com/johanbrandhorst/grpc-gateway-boilerplate/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_4315a408e23a4fd6, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "example.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	AddUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (UserService_ListUsersClient, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/example.UserService/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (UserService_ListUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserService_serviceDesc.Streams[0], "/example.UserService/ListUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceListUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_ListUsersClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type userServiceListUsersClient struct {
	grpc.ClientStream
}

func (x *userServiceListUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	AddUser(context.Context, *empty.Empty) (*User, error)
	ListUsers(*empty.Empty, UserService_ListUsersServer) error
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).ListUsers(m, &userServiceListUsersServer{stream})
}

type UserService_ListUsersServer interface {
	Send(*User) error
	grpc.ServerStream
}

type userServiceListUsersServer struct {
	grpc.ServerStream
}

func (x *userServiceListUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _UserService_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "example.proto",
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_example_4315a408e23a4fd6) }

var fileDescriptor_example_4315a408e23a4fd6 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x57, 0x02, 0xa5, 0xaa, 0x51, 0x41, 0xca, 0xa1, 0x82, 0x00, 0x92, 0x55, 0x2e, 0x08, 0x11,
	0xbb, 0x2d, 0x37, 0x7a, 0x0a, 0x08, 0x0e, 0x88, 0x03, 0x2a, 0xe2, 0xb2, 0x9b, 0x93, 0xbc, 0x39,
	0x9e, 0x52, 0xdb, 0xb2, 0x9d, 0xfe, 0xb9, 0x4d, 0x3b, 0xee, 0xd8, 0x7d, 0x95, 0x7d, 0x93, 0x7d,
	0x85, 0x7d, 0x90, 0x29, 0x4e, 0xba, 0x3f, 0xea, 0x65, 0xda, 0xc9, 0xef, 0xf9, 0xfd, 0xfe, 0x3d,
	0xcb, 0x68, 0x08, 0x1b, 0xb6, 0xd4, 0x15, 0x10, 0x6d, 0x94, 0x53, 0x51, 0xbf, 0x6b, 0xe3, 0x77,
	0x5c, 0x29, 0x5e, 0x01, 0xf5, 0xd7, 0x59, 0x7d, 0x4c, 0x61, 0xa9, 0xdd, 0xb6, 0x45, 0xc5, 0xef,
	0xbb, 0x21, 0xd3, 0x82, 0x32, 0x29, 0x95, 0x63, 0x4e, 0x28, 0x69, 0xbb, 0xe9, 0x17, 0x7f, 0xe4,
	0x09, 0x07, 0x99, 0xd8, 0x35, 0xe3, 0x1c, 0x0c, 0x55, 0xda, 0x23, 0x0e, 0xd1, 0xe3, 0x11, 0x7a,
	0xfe, 0xdf, 0x82, 0x89, 0x5e, 0xa1, 0x50, 0x14, 0x6f, 0x02, 0x1c, 0x7c, 0x1a, 0x2c, 0x42, 0x51,
	0xcc, 0xce, 0x43, 0xf4, 0xb2, 0x19, 0xfc, 0x03, 0xb3, 0x12, 0x39, 0x44, 0x1b, 0xd4, 0x4f, 0x8b,
	0xc2, 0x43, 0x47, 0xa4, 0xf5, 0x27, 0xfb, 0x70, 0xe4, 0x67, 0x13, 0x2e, 0x1e, 0x92, 0xfd, 0x32,
	0x0d, 0x6c, 0xfc, 0x6b, 0x97, 0x12, 0xd4, 0x6b, 0x4a, 0x1b, 0xa1, 0xb4, 0x28, 0x30, 0xc3, 0xb5,
	0x05, 0x13, 0xbf, 0xbd, 0xab, 0xb1, 0x53, 0xd8, 0x95, 0x80, 0x2d, 0x98, 0x15, 0x18, 0x72, 0x76,
	0x75, 0x7d, 0x11, 0xbe, 0x1e, 0x0f, 0xfd, 0x62, 0xab, 0x29, 0xad, 0x3d, 0xf7, 0x34, 0x40, 0x83,
	0x3f, 0xc2, 0xba, 0x56, 0xe9, 0x91, 0xe6, 0xbf, 0x77, 0xe9, 0xec, 0xd6, 0xbc, 0x61, 0x7b, 0x3f,
	0x1b, 0x7f, 0xf0, 0x35, 0xab, 0xaa, 0xb6, 0xc7, 0x4a, 0x1e, 0x06, 0x88, 0x1e, 0x06, 0x98, 0x04,
	0xdf, 0x2f, 0x83, 0x5d, 0x2a, 0xa3, 0xde, 0xec, 0xd9, 0x94, 0x4c, 0x3e, 0x07, 0xa1, 0xc9, 0xd0,
	0x47, 0xbe, 0xf8, 0xfb, 0x23, 0xe1, 0xcc, 0xc1, 0x9a, 0x6d, 0x71, 0xa6, 0x44, 0x05, 0x46, 0x57,
	0xcc, 0x01, 0x36, 0xa0, 0x95, 0x15, 0x4e, 0x99, 0x6d, 0x34, 0x2f, 0x9d, 0xd3, 0xf6, 0x1b, 0xa5,
	0x5c, 0xb8, 0xb2, 0xce, 0x48, 0xae, 0x96, 0xf4, 0x44, 0x95, 0x4c, 0x66, 0x86, 0xc9, 0xa2, 0x54,
	0xc6, 0x3a, 0xca, 0x8d, 0xce, 0xf7, 0x3a, 0xc9, 0x3d, 0x9d, 0xa3, 0xf4, 0x09, 0xa4, 0xf6, 0xbb,
	0xcc, 0xbb, 0x97, 0xc8, 0x5e, 0xf8, 0xf6, 0xeb, 0x4d, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x6e,
	0xd3, 0x6d, 0x65, 0x02, 0x00, 0x00,
}
