// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*AddUserRequest)(nil), "example.AddUserRequest")
	proto.RegisterType((*ListUsersRequest)(nil), "example.ListUsersRequest")
	proto.RegisterType((*User)(nil), "example.User")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0xae, 0x12, 0x31,
	0x14, 0xcd, 0x8c, 0x22, 0xa1, 0x06, 0x24, 0x5d, 0xa8, 0x4c, 0x34, 0x69, 0xc6, 0x8d, 0x21, 0xce,
	0x14, 0x70, 0x07, 0xab, 0xd1, 0x95, 0xc6, 0x85, 0xc1, 0xb8, 0x71, 0xd7, 0x99, 0xb9, 0xe9, 0xd4,
	0x0c, 0x6d, 0x6d, 0x0b, 0x48, 0xe2, 0x4a, 0xbf, 0x40, 0xfc, 0x15, 0xff, 0xc4, 0x5f, 0xf0, 0x43,
	0xcc, 0x14, 0x18, 0x1f, 0xb0, 0x7b, 0xab, 0xde, 0x73, 0xef, 0xe9, 0x39, 0xe7, 0x36, 0x45, 0x7d,
	0xf8, 0xca, 0x56, 0xba, 0x86, 0x54, 0x1b, 0xe5, 0x14, 0xee, 0x1e, 0x61, 0xf4, 0x84, 0x2b, 0xc5,
	0x6b, 0xa0, 0x4c, 0x0b, 0xca, 0xa4, 0x54, 0x8e, 0x39, 0xa1, 0xa4, 0x3d, 0xd0, 0xa2, 0x17, 0xfe,
	0x28, 0x12, 0x0e, 0x32, 0xb1, 0x5b, 0xc6, 0x39, 0x18, 0xaa, 0xb4, 0x67, 0x5c, 0xb3, 0xe3, 0x21,
	0x1a, 0x64, 0x65, 0xf9, 0xd1, 0x82, 0x59, 0xc2, 0x97, 0x35, 0x58, 0x17, 0x63, 0x34, 0x7c, 0x27,
	0xac, 0x6b, 0x5a, 0xf6, 0xd4, 0x7b, 0x88, 0xee, 0x36, 0x18, 0x0f, 0x50, 0x28, 0xca, 0xc7, 0x01,
	0x09, 0x9e, 0xf7, 0x96, 0xa1, 0x28, 0x67, 0x3f, 0x43, 0x74, 0xbf, 0x19, 0x7c, 0x00, 0xb3, 0x11,
	0x05, 0xe0, 0x6f, 0xa8, 0x7b, 0x54, 0xc3, 0x8f, 0xd2, 0x53, 0xfa, 0x73, 0xfd, 0xa8, 0xdf, 0x0e,
	0x9a, 0x6e, 0xfc, 0x66, 0x9f, 0xa5, 0xa8, 0xe3, 0xdd, 0x30, 0xca, 0xca, 0x92, 0x30, 0xb2, 0xb6,
	0x60, 0xa2, 0xd1, 0xff, 0x9a, 0x38, 0x45, 0x5c, 0x05, 0xc4, 0x82, 0xd9, 0x80, 0x49, 0xbf, 0xff,
	0xf9, 0xfb, 0x2b, 0xc4, 0x71, 0xdf, 0xef, 0xbf, 0x99, 0xd2, 0x86, 0x62, 0xe7, 0xc1, 0x18, 0xff,
	0x08, 0x50, 0xaf, 0x8d, 0x8e, 0x47, 0xad, 0xcf, 0xe5, 0x3a, 0x97, 0x11, 0xde, 0xee, 0xb3, 0x59,
	0x1b, 0xa1, 0x21, 0x7b, 0x57, 0x1b, 0x3d, 0xf5, 0x35, 0xab, 0xeb, 0x03, 0x26, 0x4a, 0x5e, 0xc5,
	0x78, 0x80, 0xcf, 0x63, 0x4c, 0x82, 0x57, 0xbf, 0x83, 0x7d, 0x26, 0x71, 0x67, 0x76, 0x67, 0x9a,
	0x4e, 0xc6, 0x41, 0x68, 0x72, 0xf4, 0x8c, 0x2f, 0xdf, 0xbf, 0x4e, 0x38, 0x73, 0xb0, 0x65, 0x3b,
	0x92, 0x2b, 0x51, 0x83, 0xd1, 0x35, 0x73, 0x40, 0x0c, 0x68, 0x65, 0x85, 0x53, 0x66, 0x87, 0x17,
	0x95, 0x73, 0xda, 0xce, 0x29, 0xe5, 0xc2, 0x55, 0xeb, 0x3c, 0x2d, 0xd4, 0x8a, 0x7e, 0x56, 0x15,
	0x93, 0xb9, 0x61, 0xb2, 0xac, 0x94, 0xb1, 0x8e, 0x72, 0xa3, 0x8b, 0x93, 0x4e, 0x72, 0x43, 0xe7,
	0x53, 0x76, 0x8b, 0x4b, 0xd4, 0x7f, 0x80, 0xc5, 0xf1, 0x25, 0xf2, 0x7b, 0x1e, 0xbe, 0xfc, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x52, 0x7d, 0x27, 0x15, 0x75, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (UserService_ListUsersClient, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/example.UserService/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (UserService_ListUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserService_serviceDesc.Streams[0], "/example.UserService/ListUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceListUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_ListUsersClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type userServiceListUsersClient struct {
	grpc.ClientStream
}

func (x *userServiceListUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	AddUser(context.Context, *AddUserRequest) (*User, error)
	ListUsers(*ListUsersRequest, UserService_ListUsersServer) error
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) AddUser(ctx context.Context, req *AddUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedUserServiceServer) ListUsers(req *ListUsersRequest, srv UserService_ListUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).ListUsers(m, &userServiceListUsersServer{stream})
}

type UserService_ListUsersServer interface {
	Send(*User) error
	grpc.ServerStream
}

type userServiceListUsersServer struct {
	grpc.ServerStream
}

func (x *userServiceListUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _UserService_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "example.proto",
}
